VAGRANTFILE_VERSION = "2"

Vagrant.configure(VAGRANTFILE_VERSION) do |config|

  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.network :public_network
  config.vm.network :private_network, ip: "10.11.12.13"

  config.vm.hostname = "precise32.vagrantup.com"

  config.vm.provider :virtualbox do |vb|
     vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "tools/puppet/manifests"
    puppet.module_path = "tools/puppet/modules"
  end

  config.vm.synced_folder ".", "/vagrant", owner: "vagrant", group: "vagrant"

end
